#!/bin/sh
#=============================================| HEADER
#Author
#	Nicolas T
#
#Criar Pacotes tpkg
#CHANGELOG
#	(Versão 1.1)
#	- Diretório desc contendo descrições do pacote
#=============================================| END_HEADER


#=============================================| VARIAVEIS GLOBAIS
export pkgext='tpkg'

# DESABILITANDO SUPORTE A UNICODE
# PARA MELHOR PERFORMACE
export LC_ALL=C
export LANG=C
#=============================================| FUNÇÕES
CHECK_PKG(){
	local pkg_name="$@"

	if ! echo "$pkg_name" | grep -q "\b${pkgext}\b$" ; then
		printf "%s\n" "A extensão do pacoe dever ser: $pkgext"
		return 1
	fi

	if echo "$pkg_name" | grep -qE "[[:space:]]+"; then
		printf "%s\n" "Não utilize ESPAÇOS no nome do pacote."
		printf "%s\n" "Abortando a criação de pacote."
		return 1
	fi

	verify=$(echo "$pkg_name" | grep -o "-" | wc -l)
	if [ $verify -ne 2 ]; then
		printf "%s\a\n" "Erro! O formato do pacote deve ser o seguinte:"
		printf "%s\n" "NomeDoPacote-Versao-Bild.${pkgext}"
		return 1
	fi
	return 0
}

# Criação de pacotes
CREATE_PKG() {
	local pkg_name="$@"

	if [ "$VERBOSE" = '1' ] ; then
		if tar -cvf ../${pkg_name} .; then
			printf "%s\n" "O pacote foi criado em ../${pkg_name}"
			return 0
		else
			printf "%s\n" "O pacote ${pkg_name} não foi criado..."
#			exit 1
		fi
	else
		if  tar -cf ../${pkg_name} .; then
			printf "%s\n" "O pacote foi criado em ../${pkg_name}"
			return 0
		else
			printf "%s\n" "O pacote ${pkg_name} não foi criado..."
			exit 1
		fi
	fi

	return 0
}
USAGE(){
	cat <<EOF
Usage: createpkg - [OPÇÕES]

OPÇÕES
	create, -c
		Cria um pacote .tpkg. O pacote sera gerado um diretõrio acima.
	verbose•, -v
		Detalha a criação do pacote.

AUTHOR	: Nicolas
EOF
}

GENERATE_PKGDESC(){
	#criando um diretorio
	if [ ! -d "desc" ]; then
		mkdir .v desc
	fi
	printf "mantenedor: "
	read mantenedor

	cat <<EOF>desc/pkgdesc
# Nome do mantenedor do pacote
mantenedor='$mantenedor'

# Email contato
contato=''

# Nome do pacote
nomepacote=''

# Versao do programa
versao=''

# Versao da Build
build=''

# licenca de uso
licenca=''

# pequena descricao
descricao=''

# homepage do projeto
www=''

# pagina do codigo fonte
source=''
EOF
}
#===========================================| TESTE
#
if [ -z "$1" ]; then
	USAGE
fi
#PARSER
while [ -n "$1" ]; do
	case "$1" in
		create|-c)
			CMD=$1
			shift
		;;
		verbose|-v)
			VERBOSE=1 #0 OFF |1 ON
			shift
		;;
		*.tpkg)
			PKG=$1
			shift
		;;
		*)
			USAGE
			exit 1
		;;
	esac
done

#=============================================| INICIO
case "$CMD" in
	create|-c)
		if [ -z "$CMD" ]; then
			printf "%s\n" "Você precisa fornecer um nome de pacote."
			exit 1
		fi
		GENERATE_PKGDESC
		CHECK_PKG	"$PKG" || exit 1
		CREATE_PKG 	"$PKG"
	;;
esac
